import './JS/api_key';
import { openModalOops } from './JS/modal-oops';
import { openModalPopUp } from './JS/modal-pop-up';
import './JS/day_night';
import './JS/modal-menu';
import './JS/hero';
import './JS/teamModal';
import './JS/team';
import './JS/weekly';
import './JS/catalog';
import './JS/library';
